name: Build and Deploy EXE to GitHub Pages

on:
  push:
    branches:
      - master  # vagy ami a főágad neve

jobs:
  build:
    runs-on: windows-latest  # Kell Windows az .exe buildhez

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # vagy amit használsz

    - name: Build the app
      run: dotnet publish PwdHandler/PwdHandler.fsproj -c Release -r win-x64 --self-contained false -o output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
