name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Clean project
        run: dotnet clean --configuration Release
      
      - name: Rebuild project
        run: dotnet build --configuration Release --no-incremental

      - name: Publish App
        run: dotnet publish -c Debug -r win-x64 --self-contained false -o output

      - name: Create ZIP archive
        run: |
          mkdir release
          Compress-Archive -Path output\* -DestinationPath release\PwdHandler.zip

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: PwdHandler-ZIP
          path: release/PwdHandler.zip

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: PwdHandler-ZIP
          path: release

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
